const disasters = [
  {
    country: "Turkey",
    date: "2023-02-06",
    disasterType: "Earthquake",
    injured: 50000,
    death: 50000,
    casualties: 100000,
    necessity: "Shelter, Medical Aid",
    status: "Ongoing",
  },
  {
    country: "Pakistan",
    date: "2022-08-25",
    disasterType: "Flood",
    injured: 12000,
    death: 1700,
    casualties: 13700,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Haiti",
    date: "2021-08-14",
    disasterType: "Earthquake",
    injured: 12000,
    death: 2200,
    casualties: 14200,
    necessity: "Medical Aid, Shelter",
    status: "Resolved",
  },
  {
    country: "Australia",
    date: "2020-01-01",
    disasterType: "Wildfire",
    injured: 500,
    death: 34,
    casualties: 534,
    necessity: "Firefighting Resources",
    status: "Resolved",
  },
  {
    country: "Indonesia",
    date: "2018-09-28",
    disasterType: "Tsunami",
    injured: 14000,
    death: 4300,
    casualties: 18300,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Mexico",
    date: "2017-09-19",
    disasterType: "Earthquake",
    injured: 6000,
    death: 370,
    casualties: 6370,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Nepal",
    date: "2015-04-25",
    disasterType: "Earthquake",
    injured: 22000,
    death: 9000,
    casualties: 31000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Philippines",
    date: "2013-11-08",
    disasterType: "Typhoon",
    injured: 28000,
    death: 6300,
    casualties: 34300,
    necessity: "Food, Shelter",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2011-03-11",
    disasterType: "Tsunami",
    injured: 6000,
    death: 18000,
    casualties: 24000,
    necessity: "Nuclear Safety, Shelter",
    status: "Resolved",
  },
  {
    country: "Haiti",
    date: "2010-01-12",
    disasterType: "Earthquake",
    injured: 300000,
    death: 230000,
    casualties: 530000,
    necessity: "Medical Aid, Shelter",
    status: "Resolved",
  },
  {
    country: "Myanmar",
    date: "2008-05-02",
    disasterType: "Cyclone",
    injured: 55000,
    death: 138000,
    casualties: 193000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2005-08-29",
    disasterType: "Hurricane",
    injured: 25000,
    death: 1800,
    casualties: 26800,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Iran",
    date: "2003-12-26",
    disasterType: "Earthquake",
    injured: 30000,
    death: 26000,
    casualties: 56000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "India",
    date: "2001-01-26",
    disasterType: "Earthquake",
    injured: 200000,
    death: 20000,
    casualties: 220000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Venezuela",
    date: "1999-12-15",
    disasterType: "Flood",
    injured: 150000,
    death: 30000,
    casualties: 180000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Colombia",
    date: "1999-01-25",
    disasterType: "Earthquake",
    injured: 4000,
    death: 1200,
    casualties: 5200,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Papua New Guinea",
    date: "1998-07-17",
    disasterType: "Tsunami",
    injured: 2000,
    death: 2200,
    casualties: 4200,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Bangladesh",
    date: "1991-04-29",
    disasterType: "Cyclone",
    injured: 150000,
    death: 138000,
    casualties: 288000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Armenia",
    date: "1988-12-07",
    disasterType: "Earthquake",
    injured: 31000,
    death: 25000,
    casualties: 56000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Mexico",
    date: "1985-09-19",
    disasterType: "Earthquake",
    injured: 50000,
    death: 10000,
    casualties: 60000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2023-08-08",
    disasterType: "Wildfire",
    injured: 150,
    death: 12,
    casualties: 162,
    necessity: "Firefighting Resources",
    status: "Ongoing",
  },
  {
    country: "India",
    date: "2023-07-15",
    disasterType: "Flood",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Brazil",
    date: "2023-06-01",
    disasterType: "Landslide",
    injured: 300,
    death: 50,
    casualties: 350,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2023-05-10",
    disasterType: "Earthquake",
    injured: 1000,
    death: 20,
    casualties: 1020,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Italy",
    date: "2023-04-05",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Canada",
    date: "2023-03-20",
    disasterType: "Avalanche",
    injured: 50,
    death: 10,
    casualties: 60,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "New Zealand",
    date: "2023-02-28",
    disasterType: "Volcanic Eruption",
    injured: 100,
    death: 5,
    casualties: 105,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "South Africa",
    date: "2023-01-15",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Philippines",
    date: "2022-12-10",
    disasterType: "Typhoon",
    injured: 5000,
    death: 300,
    casualties: 5300,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2022-11-05",
    disasterType: "Tornado",
    injured: 200,
    death: 25,
    casualties: 225,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Indonesia",
    date: "2022-10-01",
    disasterType: "Earthquake",
    injured: 1000,
    death: 50,
    casualties: 1050,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "China",
    date: "2022-09-15",
    disasterType: "Flood",
    injured: 5000,
    death: 300,
    casualties: 5300,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Nigeria",
    date: "2022-08-10",
    disasterType: "Flood",
    injured: 2000,
    death: 100,
    casualties: 2100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Germany",
    date: "2022-07-05",
    disasterType: "Flood",
    injured: 1000,
    death: 200,
    casualties: 1200,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Afghanistan",
    date: "2022-06-01",
    disasterType: "Earthquake",
    injured: 500,
    death: 50,
    casualties: 550,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2022-05-15",
    disasterType: "Tornado",
    injured: 300,
    death: 20,
    casualties: 320,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "India",
    date: "2022-04-10",
    disasterType: "Cyclone",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Brazil",
    date: "2022-03-05",
    disasterType: "Flood",
    injured: 1000,
    death: 50,
    casualties: 1050,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2022-02-01",
    disasterType: "Earthquake",
    injured: 500,
    death: 10,
    casualties: 510,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Australia",
    date: "2022-01-15",
    disasterType: "Wildfire",
    injured: 200,
    death: 5,
    casualties: 205,
    necessity: "Firefighting Resources",
    status: "Resolved",
  },

  {
    country: "Turkey",
    date: "2023-02-06",
    disasterType: "Earthquake",
    injured: 50000,
    death: 50000,
    casualties: 100000,
    necessity: "Shelter, Medical Aid",
    status: "Ongoing",
  },
  {
    country: "Pakistan",
    date: "2022-08-25",
    disasterType: "Flood",
    injured: 12000,
    death: 1700,
    casualties: 13700,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Haiti",
    date: "2021-08-14",
    disasterType: "Earthquake",
    injured: 12000,
    death: 2200,
    casualties: 14200,
    necessity: "Medical Aid, Shelter",
    status: "Resolved",
  },
  {
    country: "Australia",
    date: "2020-01-01",
    disasterType: "Wildfire",
    injured: 500,
    death: 34,
    casualties: 534,
    necessity: "Firefighting Resources",
    status: "Resolved",
  },
  {
    country: "Indonesia",
    date: "2018-09-28",
    disasterType: "Tsunami",
    injured: 14000,
    death: 4300,
    casualties: 18300,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Mexico",
    date: "2017-09-19",
    disasterType: "Earthquake",
    injured: 6000,
    death: 370,
    casualties: 6370,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Nepal",
    date: "2015-04-25",
    disasterType: "Earthquake",
    injured: 22000,
    death: 9000,
    casualties: 31000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Philippines",
    date: "2013-11-08",
    disasterType: "Typhoon",
    injured: 28000,
    death: 6300,
    casualties: 34300,
    necessity: "Food, Shelter",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2011-03-11",
    disasterType: "Tsunami",
    injured: 6000,
    death: 18000,
    casualties: 24000,
    necessity: "Nuclear Safety, Shelter",
    status: "Resolved",
  },
  {
    country: "Haiti",
    date: "2010-01-12",
    disasterType: "Earthquake",
    injured: 300000,
    death: 230000,
    casualties: 530000,
    necessity: "Medical Aid, Shelter",
    status: "Resolved",
  },
  {
    country: "Myanmar",
    date: "2008-05-02",
    disasterType: "Cyclone",
    injured: 55000,
    death: 138000,
    casualties: 193000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2005-08-29",
    disasterType: "Hurricane",
    injured: 25000,
    death: 1800,
    casualties: 26800,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Iran",
    date: "2003-12-26",
    disasterType: "Earthquake",
    injured: 30000,
    death: 26000,
    casualties: 56000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "India",
    date: "2001-01-26",
    disasterType: "Earthquake",
    injured: 200000,
    death: 20000,
    casualties: 220000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Venezuela",
    date: "1999-12-15",
    disasterType: "Flood",
    injured: 150000,
    death: 30000,
    casualties: 180000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Colombia",
    date: "1999-01-25",
    disasterType: "Earthquake",
    injured: 4000,
    death: 1200,
    casualties: 5200,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Papua New Guinea",
    date: "1998-07-17",
    disasterType: "Tsunami",
    injured: 2000,
    death: 2200,
    casualties: 4200,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Bangladesh",
    date: "1991-04-29",
    disasterType: "Cyclone",
    injured: 150000,
    death: 138000,
    casualties: 288000,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Armenia",
    date: "1988-12-07",
    disasterType: "Earthquake",
    injured: 31000,
    death: 25000,
    casualties: 56000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Mexico",
    date: "1985-09-19",
    disasterType: "Earthquake",
    injured: 50000,
    death: 10000,
    casualties: 60000,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2023-08-08",
    disasterType: "Wildfire",
    injured: 150,
    death: 12,
    casualties: 162,
    necessity: "Firefighting Resources",
    status: "Ongoing",
  },
  {
    country: "India",
    date: "2023-07-15",
    disasterType: "Flood",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Brazil",
    date: "2023-06-01",
    disasterType: "Landslide",
    injured: 300,
    death: 50,
    casualties: 350,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2023-05-10",
    disasterType: "Earthquake",
    injured: 1000,
    death: 20,
    casualties: 1020,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Italy",
    date: "2023-04-05",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Canada",
    date: "2023-03-20",
    disasterType: "Avalanche",
    injured: 50,
    death: 10,
    casualties: 60,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "New Zealand",
    date: "2023-02-28",
    disasterType: "Volcanic Eruption",
    injured: 100,
    death: 5,
    casualties: 105,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "South Africa",
    date: "2023-01-15",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Philippines",
    date: "2022-12-10",
    disasterType: "Typhoon",
    injured: 5000,
    death: 300,
    casualties: 5300,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2022-11-05",
    disasterType: "Tornado",
    injured: 200,
    death: 25,
    casualties: 225,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Indonesia",
    date: "2022-10-01",
    disasterType: "Earthquake",
    injured: 1000,
    death: 50,
    casualties: 1050,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "China",
    date: "2022-09-15",
    disasterType: "Flood",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Nigeria",
    date: "2022-08-10",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Germany",
    date: "2022-07-05",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2022-06-01",
    disasterType: "Tornado",
    injured: 150,
    death: 10,
    casualties: 160,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "India",
    date: "2022-05-15",
    disasterType: "Cyclone",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Brazil",
    date: "2022-04-10",
    disasterType: "Landslide",
    injured: 300,
    death: 50,
    casualties: 350,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2022-03-05",
    disasterType: "Earthquake",
    injured: 1000,
    death: 20,
    casualties: 1020,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Italy",
    date: "2022-02-01",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Canada",
    date: "2022-01-15",
    disasterType: "Avalanche",
    injured: 50,
    death: 10,
    casualties: 60,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "New Zealand",
    date: "2021-12-10",
    disasterType: "Volcanic Eruption",
    injured: 100,
    death: 5,
    casualties: 105,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "South Africa",
    date: "2021-11-05",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Philippines",
    date: "2021-10-01",
    disasterType: "Typhoon",
    injured: 5000,
    death: 300,
    casualties: 5300,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2021-09-15",
    disasterType: "Tornado",
    injured: 200,
    death: 25,
    casualties: 225,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Indonesia",
    date: "2021-08-10",
    disasterType: "Earthquake",
    injured: 1000,
    death: 50,
    casualties: 1050,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "China",
    date: "2021-07-05",
    disasterType: "Flood",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Nigeria",
    date: "2021-06-01",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Germany",
    date: "2021-05-15",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "United States",
    date: "2021-04-10",
    disasterType: "Tornado",
    injured: 150,
    death: 10,
    casualties: 160,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "India",
    date: "2021-03-05",
    disasterType: "Cyclone",
    injured: 5000,
    death: 200,
    casualties: 5200,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Brazil",
    date: "2021-02-01",
    disasterType: "Landslide",
    injured: 300,
    death: 50,
    casualties: 350,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "Japan",
    date: "2021-01-15",
    disasterType: "Earthquake",
    injured: 1000,
    death: 20,
    casualties: 1020,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "Italy",
    date: "2020-12-10",
    disasterType: "Flood",
    injured: 200,
    death: 15,
    casualties: 215,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
  {
    country: "Canada",
    date: "2020-11-05",
    disasterType: "Avalanche",
    injured: 50,
    death: 10,
    casualties: 60,
    necessity: "Search and Rescue",
    status: "Resolved",
  },
  {
    country: "New Zealand",
    date: "2020-10-01",
    disasterType: "Volcanic Eruption",
    injured: 100,
    death: 5,
    casualties: 105,
    necessity: "Shelter, Medical Aid",
    status: "Resolved",
  },
  {
    country: "South Africa",
    date: "2020-09-15",
    disasterType: "Flood",
    injured: 3000,
    death: 100,
    casualties: 3100,
    necessity: "Food, Clean Water",
    status: "Resolved",
  },
];

export default disasters;